server:
  port: 9527
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
    ip-address: true
info:
  app.name: jokerdig-springcloud
  company.name: jokerdig.com
# zuul
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: spirngcloud-provider-dept #不能使用该路径访问 "*"为忽略所有
  prefix: /jokerdig #设置公共的前缀
