server:
  port: 80

# Eureka
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002,http://eureka7003.com:7003
# 开启服务降级
feign:
  hystrix:
    enabled: true
