# 比如我们在配置文件中指定使用dev环境，可以通过设置不同端口来测试
# 我们启动springBoot 就可以看到已经切换到dev下的配置了
#spring:
#  profiles:
#    active: dev

# 方式二 多文档模块
server:
  port: 8081

# 激活开发端口
spring:
  profiles:
    active: dev
---
server:
  port: 8082
spring:
  profiles: test
---
server:
  port: 8083
spring:
  profiles: dev